//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProductTable1.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class ProductdbModel : DbContext
    {
        public ProductdbModel()
            : base("name=ProductdbModel")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<CategoryTable> CategoryTables { get; set; }
        public virtual DbSet<ProductTable> ProductTables { get; set; }
        
        public virtual ObjectResult<Product_Result> Product()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Product_Result>("Product");
        }
    }
}
